at svn trunk revision 16352

diff --git a/tools/regtesting/do_regtest b/tools/regtesting/do_regtest
--- a/tools/regtesting/do_regtest
+++ b/tools/regtesting/do_regtest
@@ -200,7 +200,8 @@ if [[ $dir_triplet == *valgrind* ]] ; then
    job_max_time=${job_max_time:-7200}
 else
    valgrindstring=""
-   job_max_time=${job_max_time:-600}
+#1800 for testing on slower hardware (e.g. older ARM) or hyperthreaded systems, normally regtests should be faster
+   job_max_time=${job_max_time:-1800} 
 fi
 
 if [[ $cp2k_version == p* ]] ; then
@@ -210,7 +211,11 @@ else
 fi
 
 if [[ $numprocs > 1 ]] ; then
-    cp2k_run_prefix=${cp2k_run_prefix:-"${mpiexec} -np ${numprocs} ${valgrindstring}"}
+    if [[ "$farming" == "yes" ]]; then
+       cp2k_run_prefix=${cp2k_run_prefix:-"${mpiexec} -np ${maxtasks} ${valgrindstring}"}
+    else
+       cp2k_run_prefix=${cp2k_run_prefix:-"${mpiexec} -np ${numprocs} ${valgrindstring}"}
+    fi
 else
     cp2k_run_prefix=${cp2k_run_prefix:-"${valgrindstring}"}
 fi
@@ -1057,8 +1062,10 @@ EOF
    done
    printf "&END FARMING\n" >> ${dir_out}/farming.inp
    echo "Running farming for $ijob jobs"
-   ${cp2k_prefix} ${dir_base}/${cp2k_dir}/exe/${dir_triplet}/cp2k.${cp2k_version} farming.inp ${cp2k_postfix} >& farming.out
-   if [[ $? ]]; then # on failed farming, provide info
+   ${cp2k_prefix} ${dir_base}/${cp2k_dir}/exe/${dir_triplet}/cp2k.${cp2k_version} farming.inp ${cp2k_postfix} < /dev/null >& farming.out
+   if (( $? )); then # on failed farming, provide info
+      echo "farming went fine"
+   else
       echo "==================== Farming terminated with an error, dumping output  ========================"
       cat farming.out    
       echo "==============================================================================================="
